name: 🐞 Bug report
description: Report a bug/issue
labels: [bug]
body:

  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug on CheatBreaker!
        
        - Please check if your issue was addressed already in another issue or on our [Self Diagnostics page](https://docs.cheatbreaker.net/category/self-diagnostics)
        - Provide as many details as possible. Simply saying "X crashes" or "X gives bug" isn't enough!
        - Paste logs into the backticks (``)
        - Please note that the launcher log file may include your system username. If thats something you don't want to share publicly, you can send the file to our support email (`support@cheatbreaker.net`), or simply remove every mention of your system username manually

  - type: textarea
    attributes:
      label: Describe the bug
      description: A concise description of what you're experiencing
    validations:
      required: true

  - type: textarea
    attributes:
      label: Keyword search
      description: Keywords you used to search for your issue
    validations:
      required: true

  - type: textarea
    attributes:
      label: Solutions tried
      description: |
        What did you do to try to solve the issue?

        Use [Self Diagnostics page](https://docs.cheatbreaker.net/category/self-diagnostics) if you haven't tried anything.
    validations:
      required: true 

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior
      description: |
        There is no such thing as no steps to reproduce. Be specific.
        
        Don't know specifics? Just describe what you were doing prior to your issue.
        
        examples:
          1. Go to '...'
          2. Click on '...'
          3. Scroll down to '...'
          4. See error '...'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: macOS 13.3.1
          - **Game version**: 1.7.10
          - **Game build number**: 32617e9
          - **Launcher version**: 2.3.4
          - **JRE version**: 8u111
      value: |
          OS: 
          Game version: 
          Game build number: 
          Launcher version: 
          JRE version: 
      render: markdown
    validations:
      required: true

  - type: textarea
    attributes:
      label: Log file
      description: |
        View [how to get the log file](https://docs.cheatbreaker.net/self-diagnostics/overview)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in
    validations:
      required: false
