name: 🐞 Bug report
description: Report a bug/issue
labels: [bug]
body:

  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug on Offline CheatBreaker!
        
        - Please check if your issue was addressed already in another issue or on our [Self Diagnostics page](https://self-diagnostics.offlinecheatbreaker.com)
        - Provide as many details as possible. Simply saying "X crashes" or "X gives bug" isn't enough!
        - Paste logs into the backticks (```)

  - type: textarea
    attributes:
      label: Describe the bug
      description: A concise description of what you're experiencing
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior
      description: |
        examples:
          1. Go to '...'
          2. Click on '...'
          3. Scroll down to '...'
          4. See error '...'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: macOS 12.2.1
          - **Game version**: 1.7.10
          - **Game build number**: 33e6279
          - **Launcher version**: 2.0.0
      value: |
          OS: 
          Game version: 
          Game build number: 
          Launcher version: 
      render: markdown
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in
    validations:
      required: false
